### PR TITLE
use native crypto when available

### LINKED ISSUE #52: Ability to use browser's native implementation
With the Web Cryptography API becoming a W3C Recommendation as of 26th of January of 2017, we could safely implement `pbkdf2` natively for some browsers (i.e. Chrome and Firefox). I know we are browserifying `crypto` here, but maybe we could fallback to the native methods if implemented.

Would you be interested in having such a fallback in this repo? It's pretty popular and other people seem to use it a lot in the browser. Here's how I implemented it for [github.com/jjperezaguinaga/deniable.website](https://github.com/jjperezaguinaga/deniable-website).

```
const pbkdf2Native = (password, salt, iterations, digest, mode, keylen) =>
    (window.crypto.subtle||window.crypto.webkitSubtle).importKey('raw', password, {name: 'PBKDF2'}, false, ['deriveKey'])
        .then(baseKey => (window.crypto.subtle||window.crypto.webkitSubtle).deriveKey({name: 'PBKDF2', salt, iterations, hash: digest, baseKey, {'name': mode, 'length': keylen*8}, true, ['encrypt', 'decrypt']))
        .then(key => (window.crypto.subtle||window.crypto.webkitSubtle).exportKey('raw', key))
```

I can make a PR to detect window and leverage on it based on the options given, since it seems the API has some limitations (e.g. keylen for mode has to be either 128 or 256 bits, see https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/deriveKey). You can see how [lesspass](https://github.com/lesspass/core/blob/master/src/pbkdf2.js) is using it alongside this repository for a reference of what we could do.

👋 @jprichardson!

### PR DESCRIPTION
**Pull request by calvinmetcalf**
fixes #52, mostly based on my code from [native-crypto](https://github.com/calvinmetcalf/native-crypto)

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
also #18

**Comment by calvinmetcalf** [comment]
since async is only used in browsers had to remove it from the coverage tests

**Comment by calvinmetcalf** [comment]
and we're green, one thing though that concerns me is that now environments like mobile safari while be drastically slower compared to environments that have subtle crypto and in all likelihood going to freeze the app, so thinking about ways to make it non blocking are probably a good idea as a next step.

**Comment by calvinmetcalf** [comment]
anyway but that would be a whole different thing

**Comment by dcousens** [comment]
Going to close and prefer just https://github.com/crypto-browserify/pbkdf2/pull/54 - as much to review tbh

**Pull request closed without merging**
