### PR TITLE
change old (<=0.10) node detection

### PR DESCRIPTION
**Pull request by fanatid**
Not sure that you will agree with export changes, but I ready remove this.

### CODE REVIEW

**Comment by dcousens** [comment]
LGTM.
ping @calvinmetcalfe was there any reason not to do it like this?

**Comment by calvinmetcalf** [comment]
the current version will always work while the updated version will probably work, I can't see this as being much of a speed up considering the a single round of pbkdf2 is by definition a small fraction of the total run time of the eventual computation

**Comment by fanatid** [comment]
Updated.
@calvinmetcalf I returned check for digest support through `pbkdf2Sync`, but remove `isNode10` call from every call `pbkdf2Sync/pbkdf2`. It should give little speed-up.

**Comment by calvinmetcalf** [comment]
so yes it will add a speed up to the first call, but a slowdown for every program that requires this module, previously the has was calculated only the first time pbkdf2 was called and then never calculated again.  I'm not convinced that removing that one function call if statement is much of a speedup in the first place...

**Comment by fanatid** [comment]
Agree `isNode10` has cache and I sure that function call will be very fast, but main idea now that we don't need wrapper for node > 0.10

**Comment by calvinmetcalf** [comment]
ok but your way of testing slows down the start up of every program that requires this module...

**Comment by fanatid** [comment]
I don't understand...
IIFE will be called once, `require` caches this.
```shell
$ cat a.js 
require('./x')
require('./b')
$ cat b.js 
require('./x')
$ cat x.js 
var f = (function () {
  console.log('h1')
  return true
})()

module.exports = f ? 1 : 0
$ node a.js 
h1
```

**Comment by calvinmetcalf** [comment]
yes but it will be called even if somebody never uses pbkdf2 instead of the
first time pbkdf2 is called.  Or put another way it will delay the startup
of the program instead of the start of the first call to this function.

**Comment by fanatid** [comment]
Oh, I see it now. Thanks @calvinmetcalf for explanation!

I see two options:
1. if we want remove wrapper for node > 0.10, we should check through process.version
2. if we want use check through `crypto.pbkdf2Sync`, we should use wrapper and close this PR

**Comment by calvinmetcalf** [comment]
yes you got it, I believe I originally used process.version, but when iojs happened the tests broke which is why I'm somewhat distrustful of the process.version testing

**Comment by calvinmetcalf** [comment]
this was merged as part of #27

**Pull request closed without merging**
