### PR TITLE
Fixes bug #48 that prevented usage with webpack: process.version was …

### PR DESCRIPTION
**Pull request by philipstanislaus**
…not defined.

All tests pass on my machine.

### CODE REVIEW

**Comment by philipstanislaus** [comment]
Build passes on travis, too: https://travis-ci.org/philipstanislaus/pbkdf2/builds/167850054

**Comment by dcousens** [comment]
LGTM,  but will wait on @calvinmetcalf

**Comment by calvinmetcalf** [comment]
are you per-change building with a no global option that prevents process from being included ?

**Comment by philipstanislaus** [comment]
@calvinmetcalf you mean the travis output? No, I did activate travis after pushing, that's why it is not included yet. Let me push a small change to trigger it again.

**Comment by philipstanislaus** [comment]
Ammending the commit message did not help, let me open another PR, see #50

**Comment by dcousens** [comment]
@philipstanislaus I believe @calvinmetcalf is asking is,  are you something weird that would otherwise cause `process` to be undefined,  since best we can tell,  webpack supports `process`.

**Comment by philipstanislaus** [comment]
You are right, I just tried to reproduce the issue in an example, and realized I had accidentally overwritten the process option with webpack.DefinePlugin. Sorry for any inconvenience this caused and thanks for your support! Closing this PR.

**Comment by philipstanislaus** [comment]
You are right, I just tried to reproduce the issue in an example, and realized I had accidentally overwritten the process option with `webpack.DefinePlugin`. Sorry for any inconvenience this caused and thanks for your support! Closing this PR.

**Pull request closed without merging**
