### PR TITLE
browser: avoid process.version split before process.browser

### PR DESCRIPTION
**Pull request by dcousens**
Should fix https://github.com/crypto-browserify/pbkdf2/issues/43,  @neil-morrison44 could you check?

### CODE REVIEW

**Comment by neil-morrison44** [comment]
@dcousens still won't work, the "process" isn't a global within the browser.
I recommend running your tests within something like a PhantomJS wrapper, so they're run on a "real" browser.

**Comment by dcousens** [comment]
@neil-morrison44 what?  Are you using browserify?  `process` should be defined.

**Comment by neil-morrison44** [comment]
@dcousens If you want this to work add an explicit dependency on https://www.npmjs.com/package/process (which has support for process.browser) and `var process = require("process")` in every file which uses it.

**Comment by dcousens** [comment]
The `bundle-test` works perfect in Chrome... w/ `process` defined.
What am I missing?

**Comment by neil-morrison44** [comment]
@dcousens ah, huh, good point. Wonder what's going wrong then... possibly not a real issue then.

**Comment by dcousens** [comment]
ping @calvinmetcalf

**Pull request merged**
