### PR TITLE
fail better when node version loaded in browser

### PR DESCRIPTION
**Pull request by calvinmetcalf**
so we don't explode when loaded in some weird enviroment

### CODE REVIEW

**Comment by dcousens** [comment]
how would this happen though?

**Comment by calvinmetcalf** [comment]
see #69 where react-native is loading the index instead of the browser

**Comment by dcousens** [comment]
Why isn't he using `require('pbkdf2/browser')`?

**Comment by calvinmetcalf** [comment]
HE isn't including anything, he's getting crypto, the issue is that that
file runs even if you don't try to use pbkdf2 specifically

**Comment by dnson** [comment]
@calvinmetcalf @dcousens  
I use some libs and these lib use pbkdf2.  When can this PR be merged?
One more point, in react-native `if (crypto.pbkdf2Sync.toString().indexOf('keylen, digest') === -1) {
  throw new Error('Unsupported crypto version')
}
`
The 'keylen, digest' will be minified to sth like a,b so it will always throw error.

**Pull request merged**
