### PR TITLE
[WIP] require browser version of create-hmac in browser.js

### PR DESCRIPTION
**Pull request by fanatid**

### CODE REVIEW

**Comment by dcousens** [comment]
Why?

**Comment by fanatid** [comment]
because `create-hmac` does same https://github.com/crypto-browserify/createHmac/blob/27f170f06fd958070d3e848afc706c4cc4debda5/browser.js#L2
it gives ability to use pure javascript pbkdf2 with pure hmac/hash

**Comment by dcousens** [comment]
And what about if I wanted javascript pbkdf2 and native HMAC?

**Comment by fanatid** [comment]
Can you describe your case?

**Comment by dcousens** [comment]
@fanatid PBKDF-SHA256 on Node 10 (though,  its not so relevant now)

**Comment by fanatid** [comment]
oh, I forgot about this :(
but I still think, that browser by default should export pure javascript version

maybe we should make something like this?
```js
function createPBKDF2 (hmac) {
 ...
}

module.exports = createPBKDF2(require('create-hmac/browser'))
module.exports.native = createPBKDF2(require('create-hmac'))
```
or move node v0.10 code to another file?

**Comment by fanatid** [comment]
Related project where would be nice have pure js pbkdf2: https://github.com/cryptocoinjs/scryptsy

**Comment by dcousens** [comment]
Why does that need pure JS pbkdf2?

**Comment by fanatid** [comment]
Honestly, I don't know :)
maybe for somebody it will be reasonable use pure js, because it easy for review
or use pure js for benchmarks

**Comment by dcousens** [comment]
NACK,  you can force `browser` via browserify if you need to IIRC?

**Comment by fanatid** [comment]
ok, I'll close this right now,
but we can back to this issue in October 2016, when node v0.10 will no longer maintenance :)

**Comment by dcousens** [comment]
:+1:

**Pull request closed without merging**
