### PR TITLE
benchmark

### PR DESCRIPTION
**Pull request by calvinmetcalf**
for use with #55

### CODE REVIEW

**Comment by fanatid** [comment]
@calvinmetcalf you forget add `bench` folder to commit :)

**Comment by calvinmetcalf** [comment]
done

**Comment by fanatid** [comment]
utACK

**Comment by fanatid** [comment]
```
$ node -v
v7.5.0
$ npm run bench

> pbkdf2@3.0.9 bench /home/kirill/projects/pbkdf2
> node bench/

password: hello
salt: world
iterations: 100
keylen: 32
digest: md5
current x 349 ops/sec ±1.06% (82 runs sampled)
old x 959 ops/sec ±2.31% (81 runs sampled)
Fastest is old

password: hello
salt: world
iterations: 100
keylen: 32
digest: sha256
current x 628 ops/sec ±0.76% (85 runs sampled)
old x 1,552 ops/sec ±5.26% (77 runs sampled)
Fastest is old

password: hello
salt: world
iterations: 10000
keylen: 70
digest: md5
current x 1.31 ops/sec ±6.87% (8 runs sampled)
old x 3.43 ops/sec ±6.03% (13 runs sampled)
Fastest is old

password: hello
salt: world
iterations: 10000
keylen: 70
digest: sha256
current x 2.00 ops/sec ±3.65% (9 runs sampled)
old x 5.55 ops/sec ±3.99% (18 runs sampled)
Fastest is old
```

**Pull request merged**
