### PR TITLE
change name

### PR DESCRIPTION
**Pull request by calvinmetcalf**
I asked on a whim a while back if the owner of pbkdf2 on npm would be willing to donate it to us and @fundon has graciously agreed to let us have it.  If we also want to change the repo name I can update the pull.

### CODE REVIEW

**Comment by dcousens** [comment]
I'm happy with this, I'll let you merge it when you can publish.

**Comment by fundon** [comment]
Looking forward.

**Comment by calvinmetcalf** [comment]
done as 3.0.3, now I'm going to publish a version 4 of pbkdf2-compat with a warning

**Comment by calvinmetcalf** [comment]
done thanks @fundon, @dcousens looks like you need to update the coveralls to point to the new repo.

**Comment by dcousens** [comment]
Cheers,  could you assign this to me? Not home atm

**Comment by calvinmetcalf** [comment]
assigned

**Pull request closed without merging**
