### PR TITLE
Adding like.. documentation?

### PR DESCRIPTION
**Pull request by fresheneesz**

### CODE REVIEW

**Comment by dcousens** [comment]
I wonder if we should just link to nodes documentation instead?

**Comment by fresheneesz** [comment]
@dcousens Is the API identical?

**Comment by dcousens** [comment]
@fresheneesz indeed that is the purpose of crypto-**browserify**.

**Comment by fresheneesz** [comment]
Ohhh, i see. Yeah a link would be great - nothing in the current readme gave any indication this was the case.

**Comment by dcousens** [comment]
Closed in favour of #33

**Pull request closed without merging**
