### PR TITLE
3.0.14

### PR DESCRIPTION
**Pull request by flaviocarvalho**
Bump version, need https://github.com/crypto-browserify/pbkdf2/commit/9132b7a81540a5743ece086bea87ada10028e05f on latest version

### CODE REVIEW

**Comment by flaviocarvalho** [comment]
@calvinmetcalf @dcousens

**Comment by calvinmetcalf** [comment]
published

**Comment by flaviocarvalho** [comment]
@calvinmetcalf Thank you! Can you update the version on `crypto-browserify` aswell?

**Comment by calvinmetcalf** [comment]
that should just update automatically

**Comment by flaviocarvalho** [comment]
Does that happen everyday or?
I would need a bump on `crypto-browserify` so that I can ask `node-libs-browser` to bump their version too.

**Comment by calvinmetcalf** [comment]
crypto-browserify has a floating version so you just need to remove any package-lock files (or the yarn equivilent) and reinstall your dependencies

**Comment by flaviocarvalho** [comment]
You're right, removing yarn.lock did it, thanks again!

**Pull request closed without merging**
