### PR TITLE
browser: delay async computation, fixes #13

### LINKED ISSUE #13: Async browser-pbkdf2
Is there a way to make the browser version of pbkdf2 truly asynchronous?

### PR DESCRIPTION
**Pull request by dcousens**
@bezreyhan is this what you mean?

In which case, I agree with you.

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
on it

**Comment by calvinmetcalf** [comment]
should be fixed

**Comment by dcousens** [comment]
cheers @calvinmetcalf,  renamed to `checkParameters`, no need to shorten the name.

**Comment by bezreyhan** [comment]
@dcousens sorry the ambiguity on the initial issue. Thanks for the quick fix!

I noticed that the async `randombytes` seems to be doing something similar. It calls `crypto.getRandomValues` then checks for a cb. Would it be better if it first checked for the cb then ran `crypto.getRandomValues` within  `process.nextTick`?

One disclaimer, I'm not sure exactly sure how `proccess.nextTick` works and why one would use that over setTimeout (I'm guessing it's similar in use to `setTimeout`)

Here are the lines I'm referring to: https://github.com/crypto-browserify/randombytes/blob/master/browser.js#L21-L27

**Comment by calvinmetcalf** [comment]
to answer your questions in reverse order

so the difference between process.nextTick and setTimeout is that process.nextTick queues the function to be run as soon as possible after you are dune with the current function, setTimeout on the other hand waits longer and allows other events a change to be emitted, in practice they are only noticeably different when used recursively as process.nextTick will still block the dom and cause it to freeze while setTimeout wont, in these 2 instances it is 6 of one half dozen of the other and they differ because different people wrote the 2 modules.

as for random bytes  making the call before we do set timeout, this is because randomBytes is not very computationally intensive so there isn't much noticeable change moving it, most of the errors it would throw are related to something wrong with your environment so we'd want to throw for those anyway, and lastly because we are lazy and doing it that way makes it easier to emulate the node api where the callback is optional without repeating code.

**Comment by bezreyhan** [comment]
@calvinmetcalf thanks for the explanation, that makes sense.

I haven't done any benchmarking with `randombytes` but I had assumed it was expensive. Do you, off hand, know if `randombytes` is relatively cheap on mobile as well?

**Comment by calvinmetcalf** [comment]
as i think about it more, the performance seems like less of a concern compared to sync throwing errors if there is a problem as the only errors that can throw are mainly one's related to something being very wrong in the browser

**Pull request merged**
